### ISSUE TITLE
Not all content types were returned for me to select

### ISSUE THREAD

**Issue by ileshmistry** [Kentico/kontent-google-sheets-add-on#16]
**Describe the bug**
Basically I'm using the add on, but when trying to retrieve the Content Types from the project, it is not listing them all

Therefore I can't select the one I was to use, it's like it is only listing a limited amount

**To Reproduce**
1. Go to Generate Sheets 
2. And you don't see the full list of Content Types

**Expected behavior**
I would expect all content types to be available to be selected or some form of search to find the type I need

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kentico-ericd** [comment]
Hey @ileshmistry!

How many content types do you have in your project? I randomly tried testing with 37 and it worked fine.. but I'm guessing you have a lot more?

Did you see any errors in your browser's **Console** or **Network** tab when you accessed the **Generate Sheet** page?

**Comment by ileshmistry** [comment]
Hi @kentico-ericd 

In this project we have around 140 and it will grow. Most of them we don't use, but for this add on we wanted to use the ones we do use :) 

When I did this, I didn't check the console, as I felt it just was showing a limited list, rather than not showing anything

**Comment by kentico-ericd** [comment]
@ileshmistry it should be fixed now 👍

**Comment by ileshmistry** [comment]
@kentico-ericd I don't see any Content Types now :( 
<img width="418" alt="Screenshot 2021-09-01 at 12 43 13" src="https://user-images.githubusercontent.com/6492273/131665820-62b40ae2-df99-4394-bc06-4feef55b9591.png">

**Comment by kentico-ericd** [comment]
@ileshmistry could the request still be running and just taking a long time? I don't see any errors in the add-on's logs.. do you see anything in the browser **Console** or **Network** tab?

**Comment by kentico-ericd** [comment]
I found out that it was caused by a GAS limitation: https://developers.google.com/workspace/add-ons/concepts/cards#card_anatomy. The content type names were added as a widget to a single section, and a section can only have 100 widgets. I've updated the UI and although the appearance is different, each widget has its own section and you can view 100+ content types without issue.

Let me know if it's working for you!

**Comment by ileshmistry** [comment]
@kentico-ericd 
It's now displaying a lot more Content Types for me thanks. 

However it doesn't show them all for me :( 

It's still missing about 50 more Content Types.

**Comment by kentico-ericd** [comment]
I think that there was also a limitation on the number of sections per card :sweat_smile: I've added full pagination so that you can see 30 types at a time along with the total at the top. Can you try it now?

**Comment by ileshmistry** [comment]
We had 137 Content Types. Works well for me, thanks Eric. Awesome job! 

Minor point, if it is easy to do, can the buttons be swapped around and maybe make the colours more easier to know which button to press? 

For me the Next button was white and the previous button dark grey. 
<img width="290" alt="Screenshot 2021-09-01 at 19 57 25" src="https://user-images.githubusercontent.com/6492273/131728430-44d43c3b-a564-4b94-9e3f-e714c0ad6fbd.png">

**Comment by kentico-ericd** [comment]
Glad it works! It's really weird, I noticed that when testing the button order and their colors almost seemed to changed at random.. with the current version this is what I see:

![chrome_84CZ1q0ABe](https://user-images.githubusercontent.com/25795122/131729399-fd579312-3d33-4a6a-9ab2-54ce9c99f78e.png)

But I will monitor it and see if I can nail down what's going on here 👍
